---
- name: Install vnstat
  apt:
    name: vnstat
    state: present

- name: Configure vnstat
  lineinfile:
    path: /etc/vnstat.conf
    regexp: ^Interface
    line: "Interface {{ ansible_default_ipv4.interface }}"
  notify: vnstat restart

- name: Start and enable vnstat
  service:
    name: vnstat
    state: started
    enabled: yes
