---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Remove default repos (sources.list)
  file:
    path: /etc/apt/sources.list
    state: absent
  
- name: Add repos
  apt_repository:
    repo: "{{ item }}"
    filename: "{{ role_name }}"
  with_items:
    - "{{ repos }}"
    - "{{ repos_additional }}"
