---
- name: nginx restart
  service:
    name: nginx
    state: restarted

- name: nginx reload
  service:
    name: nginx
    state: reloaded

- name: php-fpm restart
  service:
    name: php7.0-fpm
    state: restarted
