---
- name: Configure sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} {{ item.value }}"
    insertafter: "^#{{ item.name }}"
    validate: sshd -t -f %s
  with_items:
    - "{{ sshd_options }}"
    - "{{ sshd_options_additional }}"
  notify:
    - sshd restart
